groups:
- name: blackbox.rules
  rules:
  # Website/service down alerts
  - alert: WebsiteDown
    expr: probe_success == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Website/service {{ $labels.instance }} is down"
      description: "{{ $labels.instance }} has been down for more than 30 seconds."

  # Slow response time alerts
  - alert: SlowResponse
    expr: probe_duration_seconds > 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Slow response from {{ $labels.instance }}"
      description: "{{ $labels.instance }} is responding slowly ({{ $value }}s response time)."

  # SSL certificate expiration alerts
  - alert: SSLCertExpiringSoon
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7  # 7 days
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "SSL certificate expiring soon for {{ $labels.instance }}"
      description: "SSL certificate for {{ $labels.instance }} expires in less than 7 days."

  - alert: SSLCertExpiringCritical
    expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 1  # 1 day
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "SSL certificate expiring very soon for {{ $labels.instance }}"
      description: "SSL certificate for {{ $labels.instance }} expires in less than 1 day."

  # HTTP status code alerts
  - alert: UnexpectedHTTPStatus
    expr: probe_http_status_code != 200 and probe_success == 1
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Unexpected HTTP status code for {{ $labels.instance }}"
      description: "{{ $labels.instance }} returned HTTP status code {{ $value }}."
