services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=peer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.53
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:35  # 53 → 0x35
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d default"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    user: postgres
    deploy:
      resources:
        limits:
          memory: 800M        # Conservative for low-RAM system
          cpus: '0.8'         # 80% of one core max (Celeron-friendly)
        reservations:
          memory: 400M        # Guaranteed for database performance
          cpus: '0.2'         # 20% guaranteed

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.54
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:36  # 54 → 0x36
    deploy:
      resources:
        limits:
          memory: 128M        # Watchtower is very lightweight
          cpus: '0.1'         # Minimal CPU for background task
        reservations:
          memory: 64M         # Small guaranteed allocation
          cpus: '0.05'        # 5% CPU minimum

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    container_name: postgres-backup
    hostname: pg-backup
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=default
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_EXTRA_OPTS=-Z6 --schema-only --blobs
      - SCHEDULE=0 2 * * *
      - BACKUP_KEEP_DAYS=30
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    volumes:
      - postgres-backup-data:/backups
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.55
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:37  # 55 → 0x37
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M        # Sufficient for database dump buffering
          cpus: '0.3'         # 30% CPU max for backup operations
        reservations:
          memory: 128M        # Guaranteed for basic operations
          cpus: '0.1'         # 10% CPU minimum

  volume-backup:
    image: offen/docker-volume-backup:latest
    container_name: volume-backup
    hostname: vol-backup
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - BACKUP_CRON_EXPRESSION=0 3 * * *
      - BACKUP_FILENAME=backup-%Y%m%d-%H%M%S.tar.gz
      - BACKUP_RETENTION_DAYS=30
      - BACKUP_STOP_DURING_BACKUP_LABEL=docker-volume-backup.stop-during-backup=true
    volumes:
      - postgres-data:/backup/postgres-data:ro
      - /opt/homelab/backups/postgres:/backup/postgres:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/homelab/backups/volumes:/archive
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.57
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:39  # 57 → 0x39
    healthcheck:
      test: ["CMD", "pgrep", "-f", "backup"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M        # Backup can spike but should be limited
          cpus: '0.3'         # Backup I/O intensive but short bursts
        reservations:
          memory: 128M        # Minimal guaranteed
          cpus: '0.05'        # Very low CPU when idle

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.58
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:3a  # 58 → 0x3A
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 300M        # pgAdmin web interface (HomeLab usage)
          cpus: '0.25'        # Light web interface
        reservations:
          memory: 150M        # Reasonable guarantee
          cpus: '0.05'        # Minimal CPU when idle

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    volumes:
      - alertmanager-data:/alertmanager
      - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.56
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:38  # 56 → 0x38
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://${NETWORK_PREFIX:-192.168.5}.56'
      - '--web.listen-address=0.0.0.0:80'
      - '--cluster.listen-address=0.0.0.0:9094'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 200M        # AlertManager for notifications
          cpus: '0.2'         # Light alerting service
        reservations:
          memory: 100M        # Reasonable guarantee
          cpus: '0.05'        # Minimal CPU when idle

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    hostname: blackbox
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./configs/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    command:
      - '--web.listen-address=0.0.0.0:80'
      - '--config.file=/etc/blackbox_exporter/config.yml'
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.61
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:3d  # 61 → 0x3D
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 100M        # Lightweight HTTP/TCP/DNS prober
          cpus: '0.1'         # Minimal CPU for periodic checks
        reservations:
          memory: 50M         # Small guaranteed allocation
          cpus: '0.02'        # 2% CPU minimum

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: "0"
    environment:
      - TZ=Europe/Rome
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_METRICS_ENABLED=true
      - GF_SERVER_HTTP_PORT=80
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.60
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:3c  # 60 → 0x3C
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 400M        # Grafana for HomeLab dashboards
          cpus: '0.4'         # Can be CPU intensive with complex dashboards
        reservations:
          memory: 200M        # Reasonable guarantee for web interface
          cpus: '0.1'         # 10% CPU minimum

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    user: "0"
    environment:
      - TZ=Europe/Rome
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/prometheus/rules:/etc/prometheus/rules:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:80'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.59
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:3b  # 59 → 0x3B
    depends_on:
      postgres-exporter:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 500M        # Prometheus needs memory for time series data
          cpus: '0.6'         # Can be CPU intensive during scraping
        reservations:
          memory: 250M        # Guaranteed for metrics storage
          cpus: '0.15'        # 15% CPU minimum

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    command:
      - '--port=80'
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.62
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:3e  # 62 → 0x3E
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 200M        # cAdvisor is lightweight monitoring
          cpus: '0.2'         # Low CPU for container metrics
        reservations:
          memory: 100M        # Small guaranteed allocation
          cpus: '0.05'        # Minimal CPU guarantee

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    hostname: pg-exporter
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - DATA_SOURCE_NAME=postgresql://admin:password@postgres:5432/default?sslmode=disable
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.64
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:40  # 64 → 0x40
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9187/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 100M        # Very lightweight metrics exporter
          cpus: '0.1'         # Minimal CPU for metrics export
        reservations:
          memory: 50M         # Small guaranteed allocation
          cpus: '0.02'        # 2% CPU minimum

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
    volumes:
      - redis-data:/data
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.63
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:3f  # 63 → 0x3F
    command:
      - redis-server
      - --appendonly yes
      - --appendfsync everysec
      - --save 900 1
      - --save 300 10
      - --save 60 10000
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 300M        # Redis with persistence and caching
          cpus: '0.2'         # Light CPU usage for caching
        reservations:
          memory: 100M        # Guaranteed memory for data
          cpus: '0.05'        # 5% CPU minimum

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    hostname: redis-exporter
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - REDIS_ADDR=redis://redis:6379
    networks:
      homelab:
        ipv4_address: ${NETWORK_PREFIX:-192.168.5}.65
        mac_address: ${MAC_NETWORK_PREFIX:-02:42:48:4C:05}:41  # 65 → 0x41
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/redis_exporter", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 50M         # Very lightweight metrics exporter
          cpus: '0.1'         # Minimal CPU for metrics export
        reservations:
          memory: 25M         # Small guaranteed allocation
          cpus: '0.02'        # 2% CPU minimum

volumes:
  postgres-data:
    driver: local
  postgres-backup-data:
    driver: local
  pgadmin-data:
    driver: local
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  alertmanager-data:
    driver: local
  redis-data:
    driver: local

networks:
  homelab:
    name: homelab
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:-eno1}
    ipam:
      config:
        - subnet: ${NETWORK_PREFIX:-192.168.5}.0/24
          gateway: ${NETWORK_PREFIX:-192.168.5}.1
