global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.3.60:80']
