global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.3.60:80']
    metrics_path: '/metrics'

  # cAdvisor for Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.3.62:8080']
    metrics_path: '/metrics'

  # Postgres exporter for database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['192.168.3.64:9187']
    metrics_path: '/metrics'
