global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus'

# AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "192.168.5.56:80"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['192.168.5.56:80']
    metrics_path: '/metrics'

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.5.60:80']
    metrics_path: '/metrics'

  # cAdvisor for Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.5.62:80']
    metrics_path: '/metrics'

  # Postgres exporter for database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['192.168.5.64:9187']
    metrics_path: '/metrics'

  # Blackbox exporter metrics endpoint
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['192.168.5.61:80']
    metrics_path: '/metrics'

  # Redis server metrics via redis_exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['192.168.5.65:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Website and service monitoring via Blackbox Exporter
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response
    static_configs:
      - targets:
        - https://google.com
        - https://github.com
        - https://docker.io
        - http://192.168.5.1  # Your router (adjust IP if needed)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.5.61:80  # Blackbox exporter address

  # Internal service monitoring via Blackbox Exporter
  - job_name: 'blackbox-internal'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://192.168.5.60  # Grafana
        - http://192.168.5.59  # Prometheus
        - http://192.168.5.56  # AlertManager
        - http://192.168.5.58  # pgAdmin
        - http://192.168.5.62  # cAdvisor
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.5.61:80
