global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.3.60:80']

  # Docker service discovery - automatically discovers containers with prometheus labels
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only scrape containers with prometheus.scrape=true label
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      # Use prometheus.port label for port, default to 80
      - source_labels: [__meta_docker_container_label_prometheus_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:${__meta_docker_container_label_prometheus_port}
      # Use container name as instance label
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: instance
        regex: /(.*)
        replacement: ${1}
      # Use prometheus.job label if set, otherwise use container name
      - source_labels: [__meta_docker_container_label_prometheus_job]
        action: replace
        target_label: job
        regex: (.+)
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: job
        regex: /(.*)
        replacement: ${1}
