global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus'

# AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:80"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:80']
    metrics_path: '/metrics'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:80']
    metrics_path: '/metrics'

  # cAdvisor for Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:80']
    metrics_path: '/metrics'

  # Postgres exporter for database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['pg-exporter:9187']
    metrics_path: '/metrics'

  # Blackbox exporter metrics endpoint
  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox:80']
    metrics_path: '/metrics'

  # Redis server metrics via redis_exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Website monitoring via Blackbox - Public sites only
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response
    static_configs:
      - targets:
        - https://google.com
        - https://github.com
        - https://docker.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:80  # Blackbox service address


  # Log Management Stack
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: '/metrics'
