global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus'

# AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "192.168.5.56:80"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['192.168.5.56:80']
    metrics_path: '/metrics'

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.5.60:80']
    metrics_path: '/metrics'

  # cAdvisor for Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.5.62:80']
    metrics_path: '/metrics'

  # Postgres exporter for database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['192.168.5.64:9187']
    metrics_path: '/metrics'
