name: Desktop CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run desktop test in Docker
        run: |
          chmod +x scripts/test_desktop_in_docker.sh
          ./scripts/test_desktop_in_docker.sh
  test-server-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make scripts executable
        run: |
          chmod +x server/*.sh desktop/*.sh scripts/tests/*.sh
      - name: Run server dry-run locally
        run: |
          ./scripts/tests/run_server_dry_run.sh
